### ISSUE TITLE
Remove/adapt issue_template.md and pull_request_template.md

### ISSUE THREAD

**Issue by davidbgk** [OpenStopCovid/openstopcovid.github.io#6]
From my recent experience, it's a bit confusing :)

**Comment by guillaumefe** [comment]
Hi ✋ Could you be more explicit, should we **add** issue_template.md and pull_request_template.md ?

**Comment by davidbgk** [comment]
Hey 👋 they are already there actually: https://github.com/OpenStopCovid/openstopcovid.github.io/tree/master/.github

But these are the default/generic ones from Jekyll which are not very pertinent in our case IMHO.

**Comment by guillaumefe** [comment]
Thanks, I'll look into it asap

**Comment by guillaumefe** [comment]
I modified pull_request_template.md to adapt to the new translation system that is in PR currently. I think issue_template.md is quite ok.

**Comment by guillaumefe** [comment]
If something more has to be done IYO, feel free to reopen. Thank you for your help!
